#!/usr/bin/env python3
"""Shared, mechanical finalize helper for the 17-mode independent build.
Inlines current skill CSS assets BYTE-FOR-BYTE into base.html (full `auto` bundle),
stamps the core-5 SHA-256 marker, writes shared sources/. Does NOT write index.html.
"""
from __future__ import annotations
import hashlib, json, re
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent
REPO = OUT
while REPO != REPO.parent and not (REPO / "skills/adaptive-html-final/manifest.json").exists():
    REPO = REPO.parent
SKILL = REPO / "skills/adaptive-html-final"
ASSETS = SKILL / "assets"

CORE = ["theme.css", "components.css", "visual-components.css", "layouts.css", "print.css"]
CONDITIONAL = ["widgets.css", "visual-html.css", "body-icons.css", "editorial-patterns.css",
               "shape-visuals.css", "workflow-visuals.css", "theme-dark.css"]
INLINE_ORDER = ["theme.css", "components.css", "visual-components.css", "widgets.css",
                "visual-html.css", "body-icons.css", "editorial-patterns.css",
                "shape-visuals.css", "workflow-visuals.css", "layouts.css", "print.css", "theme-dark.css"]


def _read(name: str) -> str:
    return (ASSETS / name).read_text(encoding="utf-8")


_core_texts = {name: _read(name) for name in CORE}
CORE_HASH = hashlib.sha256("\n".join(_core_texts[n] for n in CORE).encode("utf-8")).hexdigest()

_SLOT_ASSET = {"THEME_CSS": "theme.css", "COMPONENTS_CSS": "components.css",
               "VISUAL_COMPONENTS_CSS": "visual-components.css", "WIDGETS_CSS": "widgets.css",
               "VISUAL_HTML_CSS": "visual-html.css", "BODY_ICONS_CSS": "body-icons.css",
               "EDITORIAL_PATTERNS_CSS": "editorial-patterns.css", "SHAPE_VISUALS_CSS": "shape-visuals.css",
               "WORKFLOW_VISUALS_CSS": "workflow-visuals.css", "LAYOUTS_CSS": "layouts.css",
               "PRINT_CSS": "print.css", "THEME_DARK_CSS": "theme-dark.css"}


def _css_slots() -> dict:
    slots = {}
    for slot, asset in _SLOT_ASSET.items():
        text = _read(asset)
        if slot == "THEME_CSS":
            text = f"/* adaptive-html-final-core-css-sha256: {CORE_HASH} */\n" + text
        slots[slot] = text
    return slots


_ICONS = {item["id"]: item["svg"] for item in json.loads((ASSETS / "body-icons.json").read_text(encoding="utf-8"))}
ICON_IDS = sorted(_ICONS)


def icon(name: str) -> str:
    if name not in _ICONS:
        raise KeyError(f"unknown body-icon id: {name!r}. valid: {ICON_IDS}")
    return f'<span class="body-icon body-icon--sm">{_ICONS[name]}</span>'


def h2(num, title: str, icon_id: str) -> str:
    num_chip = f'<span class="num">{num}</span>' if num is not None else ""
    return f'<h2>{icon(icon_id)}{num_chip}{title}</h2>'


def build_page(page_relpath: str, *, title: str, description: str, body: str, json_ld: str = "", footer: str = "") -> Path:
    base = (ASSETS / "base.html").read_text(encoding="utf-8")
    repl = {"TITLE": title, "DESCRIPTION": description, "JSON_LD_BLOCK": json_ld, "BODY": body, "FOOTER": footer}
    repl.update(_css_slots())
    html = base
    for key, value in repl.items():
        html = html.replace("{{" + key + "}}", value)
    leftover = sorted(set(re.findall(r"\{\{[A-Z_]+\}\}", html)))
    if leftover:
        raise SystemExit(f"unresolved placeholder(s) in {page_relpath}: {leftover}")
    out = OUT / page_relpath
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    return out


def write_sources() -> None:
    src = OUT / "sources"
    (src / "assets").mkdir(parents=True, exist_ok=True)
    (src / "profile.json").write_text(json.dumps({"profile": "auto"}, indent=2) + "\n", encoding="utf-8")
    (src / "adaptive-html-final-manifest.json").write_text((SKILL / "manifest.json").read_text(encoding="utf-8"), encoding="utf-8")
    asset_sha = {}
    for name in CORE + CONDITIONAL:
        text = _read(name)
        (src / "assets" / name).write_text(text, encoding="utf-8")
        asset_sha[name] = hashlib.sha256(text.encode("utf-8")).hexdigest()
    integrity = {"profile": "auto", "core_css_sha256": CORE_HASH, "asset_order": CORE,
                 "conditional_asset_order": CONDITIONAL, "inline_order": INLINE_ORDER,
                 "asset_sha256": {name: asset_sha[name] for name in INLINE_ORDER},
                 "note": "Generated by _work/_finalize.py from current skills/adaptive-html-final/assets; CSS verbatim (auto bundle)."}
    (src / "css-integrity.json").write_text(json.dumps(integrity, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    write_sources()
    print("CORE_HASH =", CORE_HASH, "| sources written OK")
